// Compose version number from auto generated version
#ifndef AUTOGEN_VERSION_H
#define AUTOGEN_VERSION_H

/*--- Autogenerated ---*/
#define BUILD_NUMBER "11 bruger"
#define BUILD_DATE "2021-08-08"
/*--- Autogenerated ---*/


#define MAJOR_VERSION "1"
#define MINOR_VERSION "0"

#define NAME "Device interact"
#define VERSION_SHORT MAJOR_VERSION "." MINOR_VERSION "." BUILD_NUMBER
#define VERSION_LONG NAME " Version: " VERSION_SHORT " " BUILD_DATE " By Simon Rigét at Paragi "

//#define FILE_HASH		"c009f3afa47dc7cc2bcf789f37cdea8c91a32f5e"
#endif